### ISSUE TITLE
Logic for toggling which team is playing

### ISSUE THREAD

**Issue by samgerend** [Uwosh-Mafia/the-chosen-project#40]
- Logic for which team is playing uses an Index, when it could use the _IsPlaying boolean in the Team class. 
- When teams are created, they should stay as team1 and team2, their names should only change and one should be assigned a value of true for IsPlaying

**Comment by samgerend** [comment]
The logic right now will change the order of the teams if team two is selected to go first. Teams should stay on their respective sides that they are created (left and right) because the professor mentioned that he will just split the teams in half, so if the teams' flip spots and are on different sides than what are created, it could get confusing.

**Comment by samgerend** [comment]
I had this logic completed, but with the merge difficulties, my work got deleted.

**Comment by schaur74** [comment]
The Logic is correct regard which team is playing and the team is staying on the correct side
